pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    if (fileExists('venv')) {
                        dir('venv') {
                            deleteDir()
                        }
                    }
                }
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r project_incubator/requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh './venv/bin/python -m unittest discover project_incubator/tests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("project_incubator:latest")
                }
            }
        }

        stage('Push Docker Image') {
            environment {
                DOCKERHUB_CREDENTIALS = credentials('your-dockerhub-credentials-id')
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'DOCKERHUB_CREDENTIALS') {
                        docker.image('project_incubator:latest').push('latest')
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
