pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r project_incubator/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh './venv/bin/python3 -m pytest project_incubator/tests'
            }
        }
    }
}
